"""
doc_generator.py — Document Generation Module
================================================
Converts rich Markdown output from Agent Gamma into downloadable
documents (PDF or .md) encoded as base64 strings.

Architecture decision: base64 encoding lets the frontend trigger an
immediate browser download without persistent server storage or temp
files — fully stateless, no cleanup needed.

PDF pipeline:  Markdown → HTML (python-markdown) → Styled HTML → PDF
               (WeasyPrint) → base64
Markdown pipeline:  raw text → UTF-8 bytes → base64

All exceptions are caught so the API never crashes.
"""

import base64
import logging
import asyncio
from typing import Tuple

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-7s | %(name)s | %(message)s",
)
logger = logging.getLogger("doc_generator")


_PDF_CSS = """
@page {
    size: A4;
    margin: 2.5cm 2cm;
    @bottom-center {
        content: "X10V — Generated Document";
        font-size: 8pt;
        color: #999;
    }
}

body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #1a1a1a;
}

h1 { font-size: 22pt; font-weight: 700; color: #111; margin-top: 0.5em; margin-bottom: 0.3em; border-bottom: 2px solid #333; padding-bottom: 0.2em; }
h2 { font-size: 16pt; font-weight: 600; color: #222; margin-top: 1.2em; margin-bottom: 0.4em; border-bottom: 1px solid #ddd; padding-bottom: 0.15em; }
h3 { font-size: 13pt; font-weight: 600; color: #333; margin-top: 1em; margin-bottom: 0.3em; }

p { margin-bottom: 0.6em; }
ul, ol { margin-left: 1.5em; margin-bottom: 0.8em; }
li { margin-bottom: 0.3em; }

strong { color: #000; }
em { color: #444; }

code {
    font-family: "SF Mono", "Fira Code", "Consolas", monospace;
    font-size: 9.5pt;
    background: #f5f5f5;
    padding: 0.15em 0.35em;
    border-radius: 3px;
    border: 1px solid #e0e0e0;
}

pre {
    background: #1e1e2e;
    color: #cdd6f4;
    padding: 1em 1.2em;
    border-radius: 6px;
    font-family: "SF Mono", "Fira Code", "Consolas", monospace;
    font-size: 9pt;
    line-height: 1.5;
    overflow-x: auto;
    margin-bottom: 1em;
    white-space: pre-wrap;
    word-wrap: break-word;
}

pre code {
    background: none;
    border: none;
    padding: 0;
    color: inherit;
    font-size: inherit;
}

table {
    border-collapse: collapse;
    width: 100%;
    margin: 1em 0;
    font-size: 10pt;
}

th, td {
    border: 1px solid #ccc;
    padding: 0.5em 0.8em;
    text-align: left;
}

th {
    background: #f0f0f0;
    font-weight: 600;
}

tr:nth-child(even) { background: #fafafa; }

blockquote {
    border-left: 3px solid #888;
    padding-left: 1em;
    color: #555;
    margin: 1em 0;
}

hr {
    border: none;
    border-top: 1px solid #ddd;
    margin: 1.5em 0;
}
"""


def structured_data_to_markdown(structured_data: dict, domain: str = "general") -> str:
    """
    Convert Gamma's structured_data JSON object into clean Markdown
    suitable for PDF generation or .md download.
    """
    if not structured_data or not isinstance(structured_data, dict):
        return "# No Content\n\nThe swarm did not produce any output."

    lines = []

    # Title based on domain
    domain_titles = {
        "finance": "📈 Financial Analysis Report",
        "code": "💻 Code Analysis Report",
        "education": "📚 Study Notes",
        "general": "📋 Analysis Report",
    }
    lines.append(f"# {domain_titles.get(domain, domain_titles['general'])}")
    lines.append("")

    # Summary
    summary = structured_data.get("summary", "")
    if summary:
        lines.append("## Summary")
        lines.append(summary)
        lines.append("")

    # Timeline / Metrics table
    metrics = structured_data.get("timeline_or_metrics", [])
    if metrics and isinstance(metrics, list):
        lines.append("## Key Data")
        lines.append("")
        lines.append("| Key | Detail |")
        lines.append("|-----|--------|")
        for entry in metrics:
            if isinstance(entry, dict):
                key = str(entry.get("key", "")).replace("|", "\\|")
                value = str(entry.get("value", "")).replace("|", "\\|")
                lines.append(f"| **{key}** | {value} |")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by X10V Headless Semantic Automation*")

    return "\n".join(lines)


async def create_document(structured_data: dict, file_type: str, domain: str = "general") -> Tuple[str, str]:
    """
    Convert Gamma's structured_data into a base64-encoded document.

    Parameters
    ----------
    structured_data : dict
        The structured_data object from Gamma's verdict.
    file_type : str
        Either "pdf" or "md".
    domain : str
        The domain for titling the document.

    Returns
    -------
    tuple(str, str)
        (base64_string, mime_type)  — ready for frontend download.
        On any failure, returns a safe fallback .md instead of crashing.
    """
    markdown_content = structured_data_to_markdown(structured_data, domain)

    file_type = (file_type or "md").lower().strip()

    if file_type == "pdf":
        return await _generate_pdf(markdown_content)
    else:
        return _generate_md(markdown_content)


def _generate_md(markdown_content: str) -> Tuple[str, str]:
    """Base64-encode the raw Markdown text."""
    logger.info("📄 Generating Markdown document (%d chars)", len(markdown_content))
    b64 = base64.b64encode(markdown_content.encode("utf-8")).decode("ascii")
    return b64, "text/markdown"


async def _generate_pdf(markdown_content: str) -> Tuple[str, str]:
    """
    Pipeline: Markdown → HTML (python-markdown) → styled HTML → PDF (WeasyPrint) → base64.

    Runs the CPU-heavy conversion in a thread executor so the event loop
    stays responsive for WebSocket broadcasts.
    """
    logger.info("📄 Generating PDF document (%d chars of Markdown)", len(markdown_content))

    try:
        loop = asyncio.get_running_loop()
        b64 = await loop.run_in_executor(None, _sync_md_to_pdf, markdown_content)
        logger.info("📄 PDF generated successfully (%d base64 chars)", len(b64))
        return b64, "application/pdf"

    except ImportError as e:
        logger.warning("📄 PDF dependency missing (%s) — falling back to Markdown", e)
        return _generate_md(markdown_content)

    except Exception as e:
        logger.error("📄 PDF generation failed: %s — falling back to Markdown", e)
        # Never crash the API — degrade gracefully to .md
        return _generate_md(markdown_content)


def _sync_md_to_pdf(markdown_content: str) -> str:
    """
    Synchronous Markdown → PDF → base64 conversion.
    Isolated so it can run in a thread executor.
    """
    import markdown
    from weasyprint import HTML

    extensions = ["tables", "fenced_code", "codehilite", "toc", "nl2br"]
    html_body = markdown.markdown(markdown_content, extensions=extensions)

    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>{_PDF_CSS}</style>
</head>
<body>
    {html_body}
</body>
</html>"""

    pdf_bytes = HTML(string=full_html).write_pdf()

    if not pdf_bytes or len(pdf_bytes) < 100:
        raise ValueError(f"WeasyPrint produced invalid PDF ({len(pdf_bytes) if pdf_bytes else 0} bytes)")

    b64_str = base64.b64encode(pdf_bytes).decode("ascii")

    if b64_str.startswith("data:"):
        b64_str = b64_str.split(",", 1)[-1]

    return b64_str
